server:
  port: 8123
  servlet:
    context-path: /api
  tomcat:
    connection-timeout: 300000  # 连接超时5分钟
    threads:
      max: 200  # 最大线程数
      min-spare: 10  # 最小空闲线程数
spring:
  application:
    name: clothingPattern-backend
  profiles:
    active: dev

